# Jenkins location and login
jenkins:  http://localhost:8080
username: None  # optional
password: None  # optional

# Repository location (remote or local)
repo: file:///tmp/project-repo/

# Repository login
scm-username: None  # optional
scm-password: None  # optional

# Job to use as a template for new jobs
template: new-job-template

# Character with which to replace '/' in ref names
namesep: '-'

# Template string for new job names
# The following placeholders are available:
#   {ref}      -> expands to full ref name
#   {shortref} -> expands to the short ref name
#   {n}        -> nth backreference of the ref regex
namefmt: '{shortref}'

# If false, a job will never be overwritten if it exists
# If true, a job will be overwritten if the new configration
# differs from the old one.
overwrite: true

# State of newly created or overwritten jobs. One of:
#   true       -> jobs will be enabled
#   false      -> jobs will be disabled
#   'template' -> jobs will inherit the state of their template job
#   'sticky'   -> new jobs inherit the state of the template job -
#                 overwritten jobs keep their previous state.
enable: 'sticky'

# Literal substitute of strings in template job
# Useful for certain plugins (eg. sidebar links)
substitute:
  '@@JOB_NAME@@' : '{branch}'

# Substitutions to perform on the ref and shortref.
# The default is '@!?#&|\^_$%*': '_', which substitutes the characters
# that cannot be in a Jenkins job name with '_'.
sanitize:
  '@!?#&|\^_$%*': '_'    # replace any of @!?#&|\^_$%* with _
  're:colou?r': 'color'  # replace regex 'colou?r' with 'color'

# List of refs to ignore (regular expressions).
ignore:
  - 'refs/heads/feature/.*-nobuild'
  - 'refs/heads/scratch/.*'

# View to which new jobs should be added.
view: 'view-name'

# String to tag jobs with (no tagging by default).
tag: 'throw-away-jobs'

# Maps ref names (regular expressions) to config dictionaries that may
# overwrite any of the previously specified options. Defaults to
# "refs: '.*'".
refs:
  - 'refs/heads/release/(.*)'
  - 'refs/heads/feature/(.*)'
  - 'refs/heads/scratch/(.*)':
      'template': 'scratch-template'
      'namefmt':  'wip-{shortref}'
      'enable':   false
      'view':     'scratch-view'
      'tag':      'group-1'

# If set to true, remove all jobs that were created by jenkins-autojobs
# for which there no longer exists a branch. If set to a tag name, only
# jobs with that name will be cleaned. Defaults to false.
cleanup: true  # or 'throw-away-jobs'
